services:
  # Backend Service
  - type: web
    name: pat-backend
    env: docker
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    plan: free
    region: oregon
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: JWT_SECRET
        generateValue: true
      - key: WAHA_URL
        value: https://pat-waha.onrender.com

  # WAHA Service
  - type: web
    name: pat-waha
    env: docker
    dockerfilePath: ./Dockerfile.waha
    plan: free
    region: oregon
    envVars:
      - key: WAHA_API_URL
        value: https://pat-waha.onrender.com
